[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
raydium_contract_main = "62KXpXWH4CsFmigMvB9GUrL5nJ53rNTgoNFESKabEwrT"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "../key/uu.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
